global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: Spring Boot Application
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          application: Spring Boot Application

  - job_name: Prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9090