global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: kiii-forum-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - host.docker.internal:8080
        labels:
          application: kiii-forum-app

  - job_name: Prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9090